## Importing important libraires

In [1]:
import pandas as pd
import numpy as np

In [171]:
data = pd.read_csv('./listings.csv')

In [172]:
data.shape

(83850, 106)

there are 106 features with 83850 data points

In [173]:
# let's see the columns in the data
for d in data.columns:
    print(d)

id
listing_url
scrape_id
last_scraped
name
summary
space
description
experiences_offered
neighborhood_overview
notes
transit
access
interaction
house_rules
thumbnail_url
medium_url
picture_url
xl_picture_url
host_id
host_url
host_name
host_since
host_location
host_about
host_response_time
host_response_rate
host_acceptance_rate
host_is_superhost
host_thumbnail_url
host_picture_url
host_neighbourhood
host_listings_count
host_total_listings_count
host_verifications
host_has_profile_pic
host_identity_verified
street
neighbourhood
neighbourhood_cleansed
neighbourhood_group_cleansed
city
state
zipcode
market
smart_location
country_code
country
latitude
longitude
is_location_exact
property_type
room_type
accommodates
bathrooms
bedrooms
beds
bed_type
amenities
square_feet
price
weekly_price
monthly_price
security_deposit
cleaning_fee
guests_included
extra_people
minimum_nights
maximum_nights
minimum_minimum_nights
maximum_minimum_nights
minimum_maximum_nights
maximum_maximum_nights
minimum_ni

In [174]:
data.shape

(83850, 106)

## Removing features which are not useful

In [175]:
data = data.drop(['listing_url', 'thumbnail_url','host_url', 'medium_url', 'picture_url', 'xl_picture_url','host_thumbnail_url', 'host_picture_url' ], axis=1)
data.shape

(83850, 98)

##### URL features romoval
deleted all the coumns which contains url and drop down the features from 106 to 98. Let's explore more

In [176]:
# dropping duplicates if any
data=data.drop_duplicates(subset={"host_id","id","scrape_id"}, keep='first', inplace=False)
data.shape

(83850, 98)

In [177]:
# no duplicates found now dropping all the id columns
data = data.drop(['host_id', 'id', 'scrape_id' ], axis=1)
data.shape

(83850, 95)

In [178]:
# we need to predict price so removing the irrelevant columns which are not useful
data = data.drop([ 'instant_bookable','calendar_last_scraped', 'number_of_reviews','is_location_exact',
                  'cancellation_policy','jurisdiction_names', 'name', 'first_review', 'last_review',
                  'is_business_travel_ready' ,'license', 'requires_license','require_guest_phone_verification', 
                  'require_guest_profile_picture','host_name','number_of_reviews_ltm', 'country_code','access','transit', 
                  'security_deposit', 'experiences_offered', 'host_since', 'host_location', 'host_about','host_response_time',
                  'host_response_rate','host_has_profile_pic','host_verifications', 'host_acceptance_rate','host_is_superhost',
                  'street', 'house_rules', 'host_neighbourhood', 'host_identity_verified', 'interaction', 'neighbourhood',
                  'neighbourhood_cleansed','neighbourhood_group_cleansed','notes', 'host_listings_count', 
                  'host_total_listings_count', 'neighborhood_overview','review_scores_accuracy', 'review_scores_checkin', 
                  'review_scores_value','review_scores_location', 'review_scores_value','review_scores_communication', 
                  'review_scores_cleanliness', 'review_scores_rating','maximum_nights','minimum_minimum_nights',
                  'maximum_minimum_nights','minimum_maximum_nights','maximum_maximum_nights','minimum_nights_avg_ntm',
                  'maximum_nights_avg_ntm','calendar_updated','has_availability','space','calculated_host_listings_count',
                  'calculated_host_listings_count_entire_homes','calculated_host_listings_count_private_rooms',
                  'calculated_host_listings_count_shared_rooms', 'city','state','zipcode','market','smart_location','country',
                  'amenities', 'last_scraped', 'summary', 'availability_30', 'availability_60', 'availability_90',
                  'weekly_price', 'monthly_price'
                 ]
                 , axis=1)
data.shape

(83850, 18)

In [179]:
for column in data.columns:
    print(column)
#      'description','property_type', 'room_type', 'accommodates',
#     'bathrooms', 'bedrooms', 'beds', 'square_feet',
#     'price', 'cleaning_fee', 'guests_included', 'extra_people', 'minimum_nights',
#     'availability_365', 'reviews_per_month', 'latitude', 'longitude', 'bed_type'

description
latitude
longitude
property_type
room_type
accommodates
bathrooms
bedrooms
beds
bed_type
square_feet
price
cleaning_fee
guests_included
extra_people
minimum_nights
availability_365
reviews_per_month


#### Explanation about these features
**description** - for the text mining operations

**latitude** - longitude list for the properties

**property_type** - list of type of the properties

**room_type** - list of type of rooms

**accommodates** -number of peoples allowed to stay

**bathrooms** - number of bathroom

**bedrooms** - number of bedroom

**beds** -number of beds in a bedroom

**square_feet** - list of area of each buildings

**price** - list of price

**cleaning_fee** - cleaning fee list 

**guests_included** - list of number of guest allowed in the property

**extra_people** - list of price of extra people in the property

**minimum_nights** - list of minimum nights of booking allowed for bookin

**reviews_per_month** - Average no. of reviews listing receives per month. Used to calculate yield

In [180]:
data.shape

(83850, 18)

In [181]:
dollar_remover = ['cleaning_fee',  'price',  'extra_people']
data[dollar_remover] = data[dollar_remover].replace('[\$,]', '', regex=True)
data[dollar_remover] = data[dollar_remover].apply(pd.to_numeric, errors='coerce')

In [185]:
data.to_csv('./removed_features.csv',index=False)
data.shape

(83850, 18)